version: "3"
services:
  preprocessing:
    build: 
      context: ./preprocessing_time_series/
      dockerfile: Dockerfile
    volumes:
      - ./preprocessing_time_series:/code
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=192.168.33.124:9092
      - SCHEMA_REGISTRY_CLIENT=http://192.168.33.124:8085
    ports:
      - "8001:80"
  classification:
    build: 
      context: ./classification/
      dockerfile: Dockerfile
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=192.168.33.124:9092
      - SCHEMA_REGISTRY_CLIENT=http://192.168.33.124:8085
    volumes:
      - . ./classification:/code
    ports:
      - "8000:80"
  dataloader:
    build: 
      context: ./dataloader/
      dockerfile: Dockerfile
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=192.168.33.124:9092
      - SCHEMA_REGISTRY_CLIENT=http://192.168.33.124:8085
      - DATABASE=postgresql://postgres:postgres@192.168.33.124:5435/postgres
    volumes:
      - ./dataloader:/code